// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MainAbout: typeof import('./src/components/main/mainAbout/mainAbout.vue')['default']
    MainContent: typeof import('./src/components/main/mainContent/MainContent.vue')['default']
    MainLayout: typeof import('./src/components/main/MainLayout.vue')['default']
    MainSearch: typeof import('./src/components/main/mainSearch/MainSearch.vue')['default']
    PubAdsense: typeof import('./src/components/pub/pubAdsense/PubAdsense.vue')['default']
    PubError: typeof import('./src/components/pub/pubError/PubError.vue')['default']
    PubImage: typeof import('./src/components/pub/pubImage/PubImage.vue')['default']
    PubLoading: typeof import('./src/components/pub/pubLoading/PubLoading.vue')['default']
    PubLogo: typeof import('./src/components/pub/pubLogo/PubLogo.vue')['default']
    PubMenu: typeof import('./src/components/pub/pubMenu/PubMenu.vue')['default']
    PubMenuItem: typeof import('./src/components/pub/pubMenu/PubMenuItem.vue')['default']
    PubNav: typeof import('./src/components/pub/pubNav/PubNav.vue')['default']
    PubPagination: typeof import('./src/components/pub/pubPagination/PubPagination.vue')['default']
    PubSearch: typeof import('./src/components/pub/pubSearch/PubSearch.vue')['default']
    PubTop: typeof import('./src/components/pub/pubTop/PubTop.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanIcon: typeof import('vant/es')['Icon']
    VanPagination: typeof import('vant/es')['Pagination']
  }
}
